Update the expected inputs to match the output of the new symbiotic converter
aufover/aufover-benchmark pull request #19
Opened 2021-10-13 15:12 UTC by jamartis

TODO: the output of predator-regre-test-0003 is sometimes nondeterminic (order of the errors may differ)

2021-10-14 11:33 UTC, lzaoral commented
> For example `single-c/mem-basic-realloc/0042-realloc-plain-leak-1/` on f35 (the test doesn't fail on f34 (unless I am missing something)):
> 
> ```
> diff -u ./output-exp.txt ./output-uni.txt                                                                                                                              
> --- ./output-exp.txt	2021-10-13 15:21:30.000000000 +0200
> +++ ./output-uni.txt	2021-10-13 15:21:32.000000000 +0200
> @@ -4,4 +4,4 @@
>  0042-test.c:10: note: call stack: function main ()
>  0042-test.c:10: note: Additional Info: address: 20:0
>  0042-test.c:10: note: Additional Info: pointing to: object at Segment: [20] of size 1
> -0042-test.c:10: note: Additional Info: MO9[1] allocated at main():  %4 = call noalias i8* @malloc(i64 1) #2, !dbg !15
> +0042-test.c:10: note: Additional Info: MO9[1] allocated at main():  %4 = call noalias align 16 i8* @malloc(i64 1) #2, !dbg !17
> ```

This will be fixed when I finalize the proper printing of debug info instead of LLVM IR instructions.

2021-11-01 12:00 UTC, lzaoral commented
@jamartis The Fedora 35 Beta freeze is over so the `cppcheck` errors should be gone. Therefore, I've restarted the CI.

2021-11-08 11:48 UTC, lzaoral commented
@jamartis Could you rebase the PR to include #21? After that the CI should be green everywhere!

2021-11-25 14:49 UTC, jamartis commented
@lzaoral Can you please check this 40227fe commit to make sure that nothing important is being lost by it?

2021-11-30 14:25 UTC, vmihalko commented on tests/single-c/mem-basic-realloc/0027-realloc-from-zerosize/output-exp@symbiotic
> +
Maybe this shouldn't be here.

2021-11-30 15:02 UTC, vmihalko requested changes
LGTM - I found no change in reported errors nor in lines where errors occurred.

Change proposed in https://github.com/aufover/aufover-benchmark/pull/19#discussion_r759328881

2021-12-02 12:37 UTC, vmihalko approved these changes
LGTM!

2021-12-02 12:51 UTC, kdudka commented
Thank you all!  Merging...

2021-12-02 12:51 UTC, merged