single-c: use `gcc -fanalyzer` to increase coverage
aufover/aufover-benchmark pull request #2
Opened 2021-05-25 14:35 UTC by kdudka

Instead of checking for `gcc -fanalyzer` explicitly, we expect it
to be always available when GCC's major version is 11 or higher.

The option `-fno-diagnostics-show-caret` applies to all diagnostic
messages coming from gcc.  So it resulted in missing comments also
in the existing COMPILER_WARNING reports.

2021-05-26 20:25 UTC, lzaoral commented
LGTM! Nevertheless, could you, please, make appropriate changes to `single-c/README@mem-basic`? At the moment everything GCC related is marked as ✅ since we didn't use it for static analysis directly and, therefore, any output was ok.

Note to @lzaoral: It might be a good idea to automatise this somehow.

2021-05-26 20:28 UTC, lzaoral requested changes
See comment above. (Sorry, I forgot that reviews on GitHub are a separate thing.)

2021-05-27 07:40 UTC, kdudka commented
Thanks for review!

We should probably use different criteria for static analyzers and formal verifiers.  If a formal verification tool misses a bug (violation of the property being verified), it is usually a show stopper.  If a static analysis tool misses a bug, it is more or less expected.  After all, that was our original motivation for integrating formal verfiers.

I quickly checked the `clang` column in the table and most of the missed bugs were insufficient OOM handling and memory leaks at the end of `main()` function.  Both the classes of bugs are usually suppressed in the output of static analyzer on purpose.  In fact, neither Predator simulates OOM by default.

Since there were no false positives in the output of `gcc -fanalyzer`, I would call it good enough and just keep the check marks in the table.

2021-05-31 08:09 UTC, lzaoral commented
That sounds reasonable. Thanks again!

2021-05-31 08:09 UTC, merged